game_paths = ["~/.steamapps/Hollow Knight Silksong"]
field_ignores = [
  # "audio",
  # "clipref",
  # "color",
  # "colour",
  # "effect",
  # "font",
  # "icon",
  # "prefab",
  # "sound",
  # "sprite",
  # "tint",
  # "vibration",
  # "ui",
]

untyped_pptr_fields = [
  "Shader.m_NonModifiableTextures", # either Texture2D or Texture3D : Texture
]

class_ids = [
    "Shader",
    "Texture2D",
    "Texture3D"
]

[scripts]
"Assembly-CSharp.dll" = [
  # "CollectableItemRelicType",
  # "EnemyJournalRecord",
  # "IntReference",
  # "DamageTag",
  # "ShopItem",
  # "Quest",
  # "ToolItemBasic",
]
